---
title: "Benthic Survey Multivariate analysis"
author: "Monique White"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lme4)
library(lmerTest)
library(car)
library(emmeans)
library("FactoMineR")
library("factoextra")
library(FactoMineR)
library(factoextra)
library(vegan) #to do NMDS
library(PCAmixdata)
library(ggfortify)
library(glmmTMB) # Generalized Linear Mixed Models using Template Model Builder
library(DHARMa) # Diagnostics for Hierarchical (multi-level/mixed) regression models
library(ggpubr)
library(ggeffects) #to be able to do ggpredict
library(ggh4x) # to specify x and y axis if desired
library(MuMIn) #model selection function
library(ggrepel)

# Import and clean data
## Recruitment data
Coral_settlement_nGBR_CS <- read.csv("~/Larval recruitment resources/Data Analysis/Coral-Settlement-Northern-GBR/Coral settlement_nGBR_CS.csv") %>%
  mutate(across(15:29, ~replace_na(.x, 0))) # Read in data

Coral_settlement_nGBR <- Coral_settlement_nGBR_CS %>% 
  filter(Shelf.posn != "Coral Sea", #remove coral sea data
        !Obs %in% c(1499, 1621, 1622)) #Remove loose tiles with heavy biofouling

Coral_settlement_nGBR <- Coral_settlement_nGBR %>% 
  rename("Shelf"= Shelf.posn,
         "Year_Collected"= Year..Jan.,
         "Site_#"= Site..,
         "Acroporidae" =Acropora,
         "Pocilloporidae" = Pocillopora,
         "Poritid" = Porites) |> 
  mutate(Year_Collected = factor(Year_Collected))
  

Coral_settlement_nGBR <- Coral_settlement_nGBR |>
  filter(Shelf == "Outer" | (Shelf %in% c("Inner", "Mid") & Tile %in% as.character(1:10)))

Coral_settlement_nGBR$Year_Collected <- factor(Coral_settlement_nGBR$Year_Collected)

Coral_settlement_nGBR <- Coral_settlement_nGBR |> 
  mutate(
    Year = case_when(
      Year_Collected == "2022" ~ "2021-22",
      Year_Collected == "2023" ~ "2022-23",
      Year_Collected == "2024" ~ "2023-24",
      Year_Collected == "2025" ~ "2024-25",
      Year_Collected == "2026" ~ "2025-26"
  )) |> 
mutate(
  notes = case_when(
    notes %in% c("dislodged", "dislodged tile", "dettached tile") ~ "Dislodged",
    notes %in% c("lots of tube worms") ~ "Lots of tube worms",
    TRUE ~ notes
  ))

Coral_settlement_nGBR <- Coral_settlement_nGBR |> 
mutate(
  notes = case_when(
    !notes %in% c("Dislodged", "Lots of tube worms")~"No notes",
    TRUE ~ notes
  ))

# Benthic Data

PIT <- read_csv("PIT_50m.csv") %>%
  mutate(across(8:91, ~replace_na(.x, 0)))# Read in data

PIT <- PIT %>% 
  filter(Year %in% c("2021-22", "2022-23", "2023-24", "2024-25", "2025-26"))

PIT <- PIT |> 
  mutate(
    Site = case_when(
      Site %in% c("Vicky-HS", "Vickys") ~ "Vicky-HS",
      Site %in% c("Turtle Beach", "TurtleB-CooksP") ~ "TurtleB-CooksP",
      Site %in% c("Lag2-Trimodal", "Lagoon") ~ "Lag2-Trimodal",
      Site == "Turtle South - Front (Sargassum)" ~ "TS_Crest",
      Site == "Turtle South - Coral" ~ "TS_Back",
      Site == "Turtle North - front" ~ "TN_Crest",
      TRUE ~ Site
    ))


PIT<- PIT |> 
  mutate(
    Shelf = factor(Shelf),
    Reef = factor(Reef),
    Site = factor(Site))

join <- PIT |> 
  group_by(Year, Shelf, Reef, Site) |> 
  summarise(
    mean_aco = mean(prop_acro),
    sd_aco = sd(prop_acro),
    mean_poci = mean(prop_poci),
    sd_poci = sd(prop_poci),
    mean_por = mean(prop_pori),
    sd_por = sd(prop_pori),
    mean_macroalgae = mean(Prop_macroalgae),
    sd_macroalgae = sd(Prop_macroalgae),
    PIT = n()
  )

Combined <- left_join(Coral_settlement_nGBR, join)

## Total recuits
total_recruits <- Coral_settlement_nGBR %>%
  select(Year_Collected, Shelf, Reef, Site, Acroporidae, Pocilloporidae, Poritid, Other) %>% 
  pivot_longer(cols = 5:8, names_to = "Family", values_to = "Total")

#Order so that Other is last in Family
total_recruits <- Coral_settlement_nGBR %>% 
  select(Year_Collected, Shelf, Reef, Site, Obs, Acroporidae, Pocilloporidae, Poritid, Other) %>% 
  pivot_longer(cols = 6:9, names_to = "Family", values_to = "Total") %>%
  mutate(Family = factor(Family, levels = c("Acroporidae", "Poritid","Pocilloporidae", "Other")))

total_recruits$Year_Collected <- as.factor(total_recruits$Year_Collected)



## Family recruitment data
family_total_recruits <- Coral_settlement_nGBR %>%
  select(2:13) %>% 
  pivot_longer(cols = 9:12, names_to = "Family", values_to = "Total") |> 
  mutate(Family = factor(Family, levels = c("Acroporidae", "Poritid","Pocilloporidae", "Other")))

```

```{r}
# Step 1: Create site-by-species matrix with Site_ID
site_by_PIT <- PIT %>%
  select(
    Year, Reef, Shelf, Site, Transect, 107:117
  ) %>%
  mutate(Site_ID = paste(Year, Reef, Site, Transect, sep = "_"))

# Step 2: Metadata (KEEP Site_ID)
metadata_PIT <- site_by_PIT %>%
  select(Site_ID, Shelf, Year)

# Step 3: Species matrix
PIT_matrix <- site_by_PIT %>%
  select(
    Site_ID,
    6:16
  )

# Step 4: Remove all-zero rows BEFORE rownames
PIT_matrix_filtered <- PIT_matrix %>%
  filter(rowSums(across(-Site_ID)) > 0) %>%
  column_to_rownames("Site_ID")

# Step 5: Match metadata
PIT_metadata_filtered <- metadata_PIT %>%
  filter(Site_ID %in% rownames(PIT_matrix_filtered)) %>%
  column_to_rownames("Site_ID")

# Step 6: PERMANOVA
PIT_adonis_result1 <- adonis2(
  PIT_matrix_filtered ~ Shelf + Year, #where shelf and year are fixed effects but without interaction
  data = PIT_metadata_filtered,
  method = "bray",
  by = "term",
  permutations = 999
)
print(PIT_adonis_result1)

PIT_adonis_result <- adonis2(
  PIT_matrix_filtered ~ Shelf * Year, #includes interaction term
  data = PIT_metadata_filtered,
  method = "bray",
  by = "term",
  permutations = 999
)
print(PIT_adonis_result)

# interaction term was significant so i think it should be included.

set.seed(999)  # reproducibility

PIT_nmds <- metaMDS(
  PIT_matrix_filtered,
  distance = "bray",
  k = 2,            # 2D solution
  trymax = 100,
  autotransform = FALSE
)
```

```{r}
PIT_nmds$stress
```
Stress is 0.102

 
```{r}
nmds_scores_PIT <- as.data.frame(scores(PIT_nmds, display = "sites"))

nmds_scores_PIT$Site_ID <- rownames(nmds_scores_PIT)

nmds_scores_PIT <- nmds_scores_PIT %>%
  left_join(
    PIT_metadata_filtered %>% 
      rownames_to_column("Site_ID"),
    by = "Site_ID"
  )

Figure6A <- ggplot() +
  geom_point(data = nmds_scores_PIT, aes(NMDS1, NMDS2, colour = Shelf), size = 2, alpha = 0.8) +
  stat_ellipse(data = nmds_scores_PIT, aes(NMDS1, NMDS2, colour = Shelf), type = "t") +
  theme_classic() +
  coord_equal() +
  scale_colour_manual(values = c("#A8C85A", "#9e379f", "#C97B5F"))+
  theme(text =element_text(size =8),
        title = element_text(size = 8),
        legend.position = "bottom")+
  scale_x_continuous(limits = c(-1.1, 2.32))+
  scale_y_continuous(limits = c(-1.33, 1.63))
  #labs(x = "")+
  # scale_shape_discrete(
  #   "Deployment",
  #   labels = c("2022" = "21/22",
  #              "2023" = "22/23",
  #              "2024" = "23/24",
  #              "2025" = "24/25",
  #              "2026" = "25/26"))
```

```{r}
Figure6a <- nmds_scores_PIT |> filter(Year == "2021-22") |> 
  ggplot() +
  geom_point(aes(NMDS1, NMDS2, colour = Shelf), size = 2, alpha = 0.8) +
  stat_ellipse(aes(NMDS1, NMDS2, colour = Shelf), type = "t") +
  theme_classic() +
  coord_equal() +
  scale_colour_manual(values = c("#A8C85A", "#9e379f", "#C97B5F"))+
  theme(text =element_text(size =8),
        title = element_text(size = 8),
        axis.title.x = element_blank(),
        legend.position = "bottom")+
  labs(x = "",, title = "21/22")+
  scale_x_continuous(limits = c(-1.1, 2.32))+
  scale_y_continuous(limits = c(-1.33, 1.63))
Figure6a
  #labs(x = "")

Figure6b <- nmds_scores_PIT |> filter(Year == "2022-23") |> 
  ggplot() +
  geom_point(aes(NMDS1, NMDS2, colour = Shelf), size = 2, alpha = 0.8) +
  stat_ellipse(aes(NMDS1, NMDS2, colour = Shelf), type = "t") +
  theme_classic() +
  coord_equal() +
  scale_colour_manual(values = c("#A8C85A", "#9e379f", "#C97B5F"))+
  theme(text =element_text(size =8),
        title = element_text(size = 8),
        axis.title.x = element_blank(),
        legend.position = "bottom")+
  labs(x = "", 
       #y = "",
       title = "22/23")+
  scale_x_continuous(limits = c(-1.1, 2.32))+
  scale_y_continuous(limits = c(-1.33, 1.63))
Figure6b

Figure6c <- nmds_scores_PIT |> filter(Year == "2023-24") |> 
  ggplot() +
  geom_point(aes(NMDS1, NMDS2, colour = Shelf), size = 2, alpha = 0.8) +
  stat_ellipse(aes(NMDS1, NMDS2, colour = Shelf), type = "t") +
  theme_classic() +
  coord_equal() +
  scale_colour_manual(values = c("#A8C85A", "#9e379f", "#C97B5F"))+
  theme(text =element_text(size =8),
        title = element_text(size = 8),
        axis.title.x = element_blank(),
        legend.position = "bottom")+
  labs(title = "23/24",
       x= ""
       )+
  scale_x_continuous(limits = c(-1.1, 2.32))+
  scale_y_continuous(limits = c(-1.33, 1.63))
Figure6c

Figure6d <- nmds_scores_PIT |> filter(Year == "2024-25") |> 
  ggplot() +
  geom_point(aes(NMDS1, NMDS2, colour = Shelf), size = 2, alpha = 0.8) +
  stat_ellipse(aes(NMDS1, NMDS2, colour = Shelf), type = "t") +
  theme_classic() +
  coord_equal() +
  scale_colour_manual(values = c("#A8C85A", "#9e379f", "#C97B5F"))+
  theme(text =element_text(size =8),
        title = element_text(size = 8),
        axis.title.x = element_blank(),
        legend.position = "bottom")+
  labs(y = "", title = "24/25")+
  scale_x_continuous(limits = c(-1.1, 2.32))+
  scale_y_continuous(limits = c(-1.33, 1.63))
Figure6d
```


```{r}
PIT_envfit <- envfit(
  PIT_nmds,
  PIT_matrix_filtered,
  permutations = 999
) 

PIT_envfit <- as.data.frame(scores(PIT_envfit, display = "vectors"))


PIT_envfit <- PIT_envfit |> 
  rownames_to_column(var = "label_Benthos")


Figure6B <- ggplot()+
  geom_text_repel(
  data = PIT_envfit,
  aes(x = NMDS1, y = NMDS2, label = label_Benthos),
  inherit.aes = FALSE,
  size = 3,
  nudge_x = ifelse(PIT_envfit$NMDS1 > 0, 0.1, -0.1),
  nudge_y = ifelse(PIT_envfit$NMDS2 > 0, 0.1, -0.1),
  force = 1,
  direction = "both"
)+
  geom_segment(data = PIT_envfit, aes(x = 0, y = 0, xend=NMDS1, yend = NMDS2),
               arrow = arrow(length = unit(1/3, "picas")),
               linetype = "solid",
               linewidth = 0.6)+
   theme_classic() +
  coord_equal() +
  theme(text =element_text(size =8),
        title = element_text(size = 8),
        legend.position = "right")+
  theme_bw() +
     theme(
        panel.grid = element_blank(),
         legend.position = "right",
         text = element_text(size = 8),
        title = element_text(size = 8)
     ) +
     labs(
         x = "NMDS1",
        y = "NMDS2"
    ) +
  # labs(y = "")+
   scale_x_continuous(limits = c(-1.1, 2.32))+
  scale_y_continuous(limits = c(-1.33, 1.63))#+
    # annotate("text",
    #          x = min(scores_hellinger$NMDS1),
    #          y = min(scores_hellinger$NMDS2),              
             #label = paste0("Stress = ", round(nmds_hellinger$stress, 3)),
              #hjust = 0, vjust = 0, size = 4
             # )+
  # scale_x_continuous(limits = c(-1.75, 3.75))+
  # scale_y_continuous(limits = c(-1.5, 1.75))

Figure6A
Figure6B

Right <- ggarrange(Figure6a, Figure6b, Figure6c, Figure6d, ncol = 2, 
                   nrow = 2,
          labels = c("C", "D", "E", "F"),
          #heights = c(4, 1),
          common.legend = TRUE, legend = "right"
          )
Left <- ggarrange(Figure6A, Figure6B, ncol = 1, 
          labels = c("A", "B"),
          #heights = c(4, 1),
          common.legend = TRUE, legend = "none"
          )

ggarrange(Left, Right, widths = c(1, 1.5), 
          common.legend = TRUE, legend = "right"
          ) |> ggsave(file = "Figure6.png",
                      height = 200,
                      width = 169,
                      unit = "mm")

ggarrange(Right, Figure6B,  ncol =1, nrow = 2, 
          common.legend = TRUE, legend = "right"
          ) |> ggsave(file = "Figure61.png",
                      height = 225,
                      width = 169,
                      unit = "mm")
```