---
title: "Cleaning_data"
author: "Monique White"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(readr)
```

```{r message=FALSE}
Coral_settlement_nGBR_CS <- read.csv("~/Larval recruitment resources/Data Analysis/Coral-Settlement-Northern-GBR/Coral settlement_nGBR_CS.csv") %>%
  mutate(across(15:29, ~replace_na(.x, 0))) # Read in data

Coral_settlement_nGBR <- Coral_settlement_nGBR_CS %>% 
  filter(Shelf.posn != "Coral Sea", #remove coral sea data
        !Obs %in% c(1499, 1621, 1622)) #Remove loose tiles with heavy biofouling

Coral_settlement_nGBR <- Coral_settlement_nGBR %>% 
  rename("Shelf"= Shelf.posn,
         "Year_Collected"= Year..Jan.,
         "Site_#"= Site..,
         "Acroporidae" =Acropora,
         "Pocilloporidae" = Pocillopora,
         "Poritid" = Porites) |> 
  mutate(Year_Collected = factor(Year_Collected))

Coral_settlement_nGBR <- Coral_settlement_nGBR |>
  filter(Shelf == "Outer" | (Shelf %in% c("Inner", "Mid") & Tile %in% as.character(1:10)))

Coral_settlement_nGBR$Year_Collected <- factor(Coral_settlement_nGBR$Year_Collected)

Coral_settlement_nGBR <- Coral_settlement_nGBR |> 
  mutate(
    Year = case_when(
      Year_Collected == "2022" ~ "2021-22",
      Year_Collected == "2023" ~ "2022-23",
      Year_Collected == "2024" ~ "2023-24",
      Year_Collected == "2025" ~ "2024-25",
      Year_Collected == "2026" ~ "2025-26"
  ))
```

```{r}
# remove dislodged
Coral_settlement_nGBR <- Coral_settlement_nGBR |>
  filter(is.na(notes) | trimws(notes) == "") |>
  group_by(Year..Jan., Reef, Site) |>
  mutate(
    Tile = row_number()
  ) |>
  filter(Tile <= 10) |>
  ungroup()
```


```{r}
sample_design <- Coral_settlement_nGBR |> 
  group_by(Year, Reef, Site) |> 
  summarise(n = n()) |> 
  arrange(desc(n)) 
```

```{r}
PIT <- read_csv("PIT_50m.csv") %>%
  mutate(across(8:50, ~replace_na(.x, 0)))# Read in data

PIT <- PIT %>% 
  filter(Year %in% c("2021-22", "2022-23", "2023-24", "2024-25", "2025-26"))

PIT <- PIT |> 
  mutate(
    Site = case_when(
      Site %in% c("Vicky-HS", "Vickys") ~ "Vicky-HS",
      Site %in% c("Turtle Beach", "TurtleB-CooksP") ~ "TurtleB-CooksP",
      Site %in% c("Lag2-Trimodal", "Lagoon") ~ "Lag2-Trimodal",
      Site == "Turtle South - Front (Sargassum)" ~ "TS_Crest",
      Site == "Turtle South - Coral" ~ "TS_Back",
      Site == "Turtle North - front" ~ "TN_Crest",
      TRUE ~ Site
    )
  )
sample_joined <- left_join(sample_design2, sample_design)
```

This says that TS_Channel in 2022-23 were all removed somehow - or all had comments

```{r}
Coral_settlement_nGBR_CS |> filter(Site == "TS_Channel", Year..Jan. == "2023") # Basically all tiles had lots of tube worms in TS_CHannel in 2023
```

```{r}
notes_summary <- Coral_settlement_nGBR_CS |> 
  filter(Region == "GBRMP") |> 
  group_by(Year..Jan., Shelf.posn, Site, notes) |> 
  summarise(
    mean = mean(total),
    se = sd(total)/n()^0.5,
    n = n()
  )

Coral_settlement_nGBR |> 
  ggplot(aes(x = Site, y=total, colour = notes)) +
  geom_boxplot()+
  facet_wrap(~Year)+
  theme(axis.text.x = element_text(angle = 45))
```

