---
title: "Composition and Surface"
author: "Monique White"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
#library(lme4)
#library(lmerTest)
library(car)
library(emmeans)
library("FactoMineR")
library("factoextra")
library(FactoMineR)
library(factoextra)
library(vegan) #to do NMDS
library(PCAmixdata)
library(ggfortify)
library(glmmTMB) # Generalized Linear Mixed Models using Template Model Builder
library(DHARMa) # Diagnostics for Hierarchical (multi-level/mixed) regression models
library(ggpubr)
library(data.table) #not sure if required at this point
library(plotly) #interactive nmds

#import and clean data
Coral_settlement_nGBR_CS <- read_csv("~/Larval recruitment resources/Data Analysis/Coral-Settlement-Northern-GBR/Coral settlement_nGBR_CS.csv") %>%
  mutate(across(15:29, ~replace_na(.x, 0))) # Read in data

Coral_settlement_nGBR <- Coral_settlement_nGBR_CS %>% 
  filter(`Shelf posn` != "Coral Sea", #remove coral sea data
        !Obs %in% c(1499, 1621, 1622)) #Remove loose tiles with heavy biofouling

Coral_settlement_nGBR |> 
  filter(notes != "NA")

Coral_settlement_nGBR <- Coral_settlement_nGBR %>% 
  rename("Shelf"= `Shelf posn`,
         "Year_Collected"= `Year (Jan)`,
         "Site_#"= `Site #`,
         "Acroporidae" =Acropora,
         "Pocilloporidae" = Pocillopora,
         "Poritid" = Porites) |> 
  mutate(Year_Collected = factor(Year_Collected))

Coral_settlement_nGBR <- Coral_settlement_nGBR |>
  filter(Shelf == "Outer" | (Shelf %in% c("Inner", "Mid") & Tile %in% as.character(1:10)))

Coral_settlement_nGBR$Year_Collected <- factor(Coral_settlement_nGBR$Year_Collected)

Coral_settlement_nGBR <- Coral_settlement_nGBR |>  mutate(
    Deployment =
    case_when(
      Year_Collected == "2025" ~ "24/25",
      Year_Collected == "2024" ~ "23/24",
      Year_Collected == "2023" ~ "22/23",
      Year_Collected == "2022" ~ "21/22")
  )

# Benthic Data

PIT <- read_csv("PIT_50m.csv") %>%
  mutate(across(8:91, ~replace_na(.x, 0)))# Read in data

PIT <- PIT %>% 
  filter(Year %in% c("2021-22", "2022-23", "2023-24", "2024-25", "2025-26"))

PIT <- PIT |> 
  mutate(
    Site = case_when(
      Site %in% c("Vicky-HS", "Vickys") ~ "Vicky-HS",
      Site %in% c("Turtle Beach", "TurtleB-CooksP") ~ "TurtleB-CooksP",
      Site %in% c("Lag2-Trimodal", "Lagoon") ~ "Lag2-Trimodal",
      Site == "Turtle South - Front (Sargassum)" ~ "TS_Crest",
      Site == "Turtle South - Coral" ~ "TS_Back",
      Site == "Turtle North - front" ~ "TN_Crest",
      TRUE ~ Site
    ))


PIT<- PIT |> 
  mutate(
    Shelf = factor(Shelf),
    Reef = factor(Reef),
    Site = factor(Site))

PIT <- PIT |> 
   mutate(
    Deployment =
    case_when(
      Year == "2024-25" ~ "24/25",
      Year == "2023-24" ~ "23/24",
      Year == "2022-23" ~ "22/23",
      Year == "2021-22" ~ "21/22")
  )
```

Want to get a data frame where Acroporidae, Pocilloporidae, Poritidae, and Other are all along the top,
and then there is a column called surface with Top, Bottom, and Side

Would need to make the Top.total, side.total, and bottom.total pivot longer as well, but marry up to the current data..
```{r}
position_family_recruits <- Coral_settlement_nGBR %>%
  filter(total >0) |>  #only vegetated tiles included
  select(2:9, 15:29) %>% 
  pivot_longer(cols = 9:20, names_to = "Pos", values_to = "Total")

position_family_recruits <- position_family_recruits |> 
  mutate(Family = case_when(
      Pos %in% c("Top_Acr", "Side_Acr", "Under_Acr") ~ "Acroporidae",
      Pos %in% c("Top_Pocil", "Side_Pocil", "Under_Pocil") ~ "Pocilloporidae",
      Pos %in% c("Top_Por", "Side_Por", "Under_Por") ~ "Poritidae",
     Pos %in% c("Top_other", "Side_other", "Under_oth") ~ "Other"
  ))

position_family_recruits <- position_family_recruits |> 
  mutate(Pos = case_when(
      Pos %in% c("Top_Acr","Top_Pocil", "Top_Por", "Top_other") ~ "Top",
      Pos %in% c("Side_Pocil", "Side_Acr", "Side_Por","Side_other") ~ "Side",
      Pos %in% c("Under_Acr", "Under_Pocil", "Under_Por", "Under_oth") ~ "Bottom"
  ))
 
position_family_recruits <- position_family_recruits |>                           
mutate(Pos = factor(Pos, levels = c("Bottom", "Side", "Top")),
       Family = factor(Family, levels = c("Acroporidae", "Pocilloporidae","Poritidae", "Other")))

position_family_recruits <- position_family_recruits |> pivot_wider(names_from = Family, values_from = Total)

vegetated_surfaces <- position_family_recruits |> 
  mutate(surface = case_when(Pos == "Top"~ `Top Total`,
                              Pos == "Bottom" ~ `Under Total`,
                              Pos == "Side" ~ `Side Total`
          ))
vegetated_surfaces <- vegetated_surfaces |> 
  filter(surface > 0)
```

```{r}
SC <- vegetated_surfaces |>  
  select(Acroporidae, Pocilloporidae, Poritidae, Other) #SC = Surface composition

SC_hellinger <- decostand(SC, method = "hellinger")

environment_data <- vegetated_surfaces %>%
  select(Year_Collected, Site, Reef, Shelf, Pos) 
```

```{r}
# Bray–Curtis PERMANOVA
adonis2(SC_hellinger ~ Pos * Shelf, data = environment_data, method = "bray")

#Nested PERMANOVA
adonis2(SC_hellinger ~ Pos * Shelf, data = environment_data, method = "bray",  strata = environment_data$Reef)
```