---
title: "Pairwise Tests"
author: "Monique White"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lme4)
library(lmerTest)
library(car)
library(emmeans)
library("FactoMineR")
library("factoextra")
library(FactoMineR)
library(factoextra)
library(vegan) #to do NMDS
library(PCAmixdata)
library(ggfortify)
library(glmmTMB) # Generalized Linear Mixed Models using Template Model Builder
library(DHARMa) # Diagnostics for Hierarchical (multi-level/mixed) regression models
library(ggpubr)
library(ggeffects) #to be able to do ggpredict
library(ggh4x) # to specify x and y axis if desired
library(MuMIn) #model selection function
library(ggrepel)


# Import and clean data
## Recruitment data
Coral_settlement_nGBR_CS <- read.csv("~/Larval recruitment resources/Data Analysis/Coral-Settlement-Northern-GBR/Coral settlement_nGBR_CS.csv") %>%
  mutate(across(15:29, ~replace_na(.x, 0))) # Read in data

Coral_settlement_nGBR <- Coral_settlement_nGBR_CS %>% 
  filter(Shelf.posn != "Coral Sea", #remove coral sea data
        !Obs %in% c(1499, 1621, 1622)) #Remove loose tiles with heavy biofouling

Coral_settlement_nGBR <- Coral_settlement_nGBR %>% 
  rename("Shelf"= Shelf.posn,
         "Year_Collected"= Year..Jan.,
         "Site_#"= Site..,
         "Acroporidae" =Acropora,
         "Pocilloporidae" = Pocillopora,
         "Poritid" = Porites) |> 
  mutate(Year_Collected = factor(Year_Collected))
  

Coral_settlement_nGBR <- Coral_settlement_nGBR |>
  filter(Shelf == "Outer" | (Shelf %in% c("Inner", "Mid") & Tile %in% as.character(1:10)))

Coral_settlement_nGBR$Year_Collected <- factor(Coral_settlement_nGBR$Year_Collected)

Coral_settlement_nGBR <- Coral_settlement_nGBR |> 
  mutate(
    Year = case_when(
      Year_Collected == "2022" ~ "2021-22",
      Year_Collected == "2023" ~ "2022-23",
      Year_Collected == "2024" ~ "2023-24",
      Year_Collected == "2025" ~ "2024-25",
      Year_Collected == "2026" ~ "2025-26"
  ),
  Deployment = case_when(
      Year_Collected == "2022" ~ "21/22",
      Year_Collected == "2023" ~ "22/23",
      Year_Collected == "2024" ~ "23/24",
      Year_Collected == "2025" ~ "24/25",
      Year_Collected == "2026" ~ "25/26"
  )) |> 
mutate(
  notes = case_when(
    notes %in% c("dislodged", "dislodged tile", "dettached tile") ~ "Dislodged",
    notes %in% c("lots of tube worms") ~ "Lots of tube worms",
    TRUE ~ notes
  ))

Coral_settlement_nGBR <- Coral_settlement_nGBR |> 
mutate(
  notes = case_when(
    !notes %in% c("Dislodged", "Lots of tube worms")~"No notes",
    TRUE ~ notes
  ))

# Remove dislodged
Coral_settlement_nGBR <- Coral_settlement_nGBR |> 
filter(notes != "Dislodged")


Pocilloporidae <- Coral_settlement_nGBR %>% 
  select(Year, Shelf, 
         Reef, Site, Tile, 
         Pocilloporidae, Top_Pocil, 
         Under_Pocil, Side_Pocil, total)

Pocilloporidae_orientation <- Pocilloporidae %>% 
  rename(Top = Top_Pocil,
                   Bottom = Under_Pocil,
                   Side = Side_Pocil,
         Recruits_per_tile = total)

Pocilloporidae_orientation <- Pocilloporidae_orientation %>% 
  pivot_longer(cols = 7:9,
               names_to = "Tile_Surface",
               values_to = "Recruits")

Acroporidae <- Coral_settlement_nGBR %>% 
  select(Year, Shelf, 
         Reef, Site, Tile, 
         Acroporidae, Top_Acr, 
         Under_Acr, Side_Acr, total)

Acroporidae_orientation <- Acroporidae %>% 
  rename(Top = Top_Acr,
                   Bottom = Under_Acr,
                   Side = Side_Acr,
         Recruits_per_tile = total)

Acroporidae_orientation <- Acroporidae_orientation %>% 
  pivot_longer(cols = 7:9,
               names_to = "Tile_Surface",
               values_to = "Recruits")

Poritid <- Coral_settlement_nGBR %>% 
  select(Year, Shelf, 
         Reef, Site, Tile, 
         Poritid, Top_Por, Under_Por, 
         Side_Por, total)

Poritidae_orientation <- Poritid %>% 
  rename(Top = Top_Por,
                   Bottom = Under_Por,
                   Side = Side_Por,
         Recruits_per_tile = total) 

Poritidae_orientation <- Poritidae_orientation %>% 
  pivot_longer(cols = 7:9,
               names_to = "Tile_Surface",
               values_to = "Recruits")


# Benthic Data

PIT <- read_csv("PIT_50m.csv") %>%
  mutate(across(8:91, ~replace_na(.x, 0)))# Read in data

PIT <- PIT %>% 
  filter(Year %in% c("2021-22", "2022-23", "2023-24", "2024-25", "2025-26"))

PIT <- PIT |> 
  mutate(
    Site = case_when(
      Site %in% c("Vicky-HS", "Vickys") ~ "Vicky-HS",
      Site %in% c("Turtle Beach", "TurtleB-CooksP") ~ "TurtleB-CooksP",
      Site %in% c("Lag2-Trimodal", "Lagoon") ~ "Lag2-Trimodal",
      Site == "Turtle South - Front (Sargassum)" ~ "TS_Crest",
      Site == "Turtle South - Coral" ~ "TS_Back",
      Site == "Turtle North - front" ~ "TN_Crest",
      TRUE ~ Site
    ))

PIT<- PIT |> 
  mutate(
    Shelf = factor(Shelf),
    Reef = factor(Reef),
    Site = factor(Site))

join <- PIT |> 
  group_by(Year, Shelf, Reef, Site) |> 
  summarise(
    mean_aco = mean(prop_acro),
    sd_aco = sd(prop_acro),
    mean_poci = mean(prop_poci),
    sd_poci = sd(prop_poci),
    mean_por = mean(prop_pori),
    sd_por = sd(prop_pori),
    mean_macroalgae = mean(Prop_macroalgae),
    sd_macroalgae = sd(Prop_macroalgae),
    PIT = n()
  )

Combined <- left_join(Coral_settlement_nGBR, join)

## Total recuits
total_recruits <- Coral_settlement_nGBR %>%
  select(Year_Collected, Shelf, Reef, Site, Acroporidae, Pocilloporidae, Poritid, Other) %>% 
  pivot_longer(cols = 5:8, names_to = "Family", values_to = "Total")

#Order so that Other is last in Family
total_recruits <- Coral_settlement_nGBR %>% 
  select(Year_Collected, Shelf, Reef, Site, Obs, Acroporidae, Pocilloporidae, Poritid, Other) %>% 
  pivot_longer(cols = 6:9, names_to = "Family", values_to = "Total") %>%
  mutate(Family = factor(Family, levels = c("Acroporidae", "Poritid","Pocilloporidae", "Other")))

total_recruits$Year_Collected <- as.factor(total_recruits$Year_Collected)

## Position on tile

position_total_recruits <- Coral_settlement_nGBR %>%
  select(2:9, 15:29, 32) %>% 
  pivot_longer(cols = 21:23, names_to = "Pos", values_to = "Total")

position_total_recruits <- position_total_recruits |> 
  mutate(Pos = case_when(
      Pos == "Top.Total" ~ "Top",
      Pos == "Side.Total" ~ "Side",
      Pos == "Under.Total" ~ "Bottom"
  ))
position_total_recruits <- position_total_recruits |>                           
mutate(Pos = factor(Pos, levels = c("Bottom", "Side", "Top")))

position_total_recruits <- left_join(position_total_recruits, join)

## Family recruitment data
family_total_recruits <- Coral_settlement_nGBR %>%
  select(2:13) %>% 
  pivot_longer(cols = 9:12, names_to = "Family", values_to = "Total") |> 
  mutate(Family = factor(Family, levels = c("Acroporidae", "Poritid","Pocilloporidae", "Other")))
```

Total recruits

```{r}
nbin_total_yr2 <- glmmTMB(total ~ Shelf * Year +(1 | Reef/Site), 
        family = "nbinom2", data = Coral_settlement_nGBR)
```

```{r}
emm_shelf <- emmeans(nbin_total_yr2, ~Shelf | Year)
pairs(emm_shelf, adjust = "tukey")#has estimate whereas the response has ratio

emm_shelf_response <- emmeans(nbin_total_yr2, ~Shelf| Year, type = "response")
#create dataframe
emm_total_df <- as.data.frame(emm_shelf_response) |> 
  rename(predicted_recruits = response)
# Contrast Dataframe
emm_total_pair_df <- pairs(emm_shelf_response, adjust = "tukey")

#Calcualte additive differences in total recruits
difference_total <- emm_total_df |> 
  select(Year, Shelf, predicted_recruits) |> 
  pivot_wider(names_from = Shelf, values_from = predicted_recruits) |> 
  mutate(
    Mid_minus_Inner   = Mid - Inner,
    Outer_minus_Inner = Outer - Inner,
    Outer_minus_Mid   = Outer - Mid,
    pct_change_Mid_Inner   = 100 * (Mid - Inner)/Inner,
    pct_change_Outer_Inner = 100 * (Outer - Inner)/Inner,
    pct_change_Outer_Mid   = 100 * (Outer - Mid)/Mid
  )

difference_total
```

```{r}
# emm_year <- emmeans(nbin_total_yr2, ~Year | Shelf)
# pairs(emm_year, adjust = "tukey")
emm_year_response <- emmeans(nbin_total_yr2, ~Year|Shelf, type = "response")
pairs(emm_year_response, adjust = "tukey")
```

```{r}
nbin_Poritid_interaction <- glmmTMB(Poritid ~ Shelf*Year + (1 | Reef/Site), 
        family = "nbinom2", data = Poritid)

nbin_Pocilloporidae_interaction <- glmmTMB(Pocilloporidae ~ Shelf * Year + (1 | Reef/Site), 
        family = "nbinom2", data = Pocilloporidae)

nbin_Acroporidae_interaction <- glmmTMB(Acroporidae ~ Shelf*Year + (1 | Reef/Site), 
        family = "nbinom2", data = Acroporidae)
```

Acroporidae
```{r}
emm_acro_shelf <- emmeans(nbin_Acroporidae_interaction, ~Shelf|Year, type = "response")
pairs(emm_acro_shelf, adjust = "tukey")
#create dataframe
emm_acro_df <- as.data.frame(emm_acro_shelf) |> 
  rename(predicted_recruits = response)
# Contrast Dataframe
emm_acro_pair_df <- pairs(emm_acro_shelf, adjust = "tukey")

#Calcualte additive differences in total recruits
difference_acro <- emm_acro_df |> 
  select(Year, Shelf, predicted_recruits) |> 
  pivot_wider(names_from = Shelf, values_from = predicted_recruits) |> 
  mutate(
    Mid_minus_Inner   = Mid - Inner,
    Outer_minus_Inner = Outer - Inner,
    Outer_minus_Mid   = Outer - Mid,
    pct_change_Mid_Inner   = 100 * (Mid - Inner)/Inner,
    pct_change_Outer_Inner = 100 * (Outer - Inner)/Inner,
    pct_change_Outer_Mid   = 100 * (Outer - Mid)/Mid
  )

difference_acro

emm_acro_year <- emmeans(nbin_Acroporidae_interaction, ~Year|Shelf, type = "response")
pairs(emm_acro_year, adjust = "tukey")
```


Pocilloporidae

```{r}
emm_poci_shelf <- emmeans(nbin_Pocilloporidae_interaction, ~Shelf | Year, type = "response")
pairs(emm_poci_shelf, adjust = "tukey")

#create dataframe
emm_poci_df <- as.data.frame(emm_poci_shelf) |> 
  rename(predicted_recruits = response)
# Contrast Dataframe
emm_poci_pair_df <- pairs(emm_poci_shelf, adjust = "tukey")

#Calcualte additive differences in total recruits
difference_poci <- emm_poci_df |> 
  select(Year, Shelf, predicted_recruits) |> 
  pivot_wider(names_from = Shelf, values_from = predicted_recruits) |> 
  mutate(
    Mid_minus_Inner   = Mid - Inner,
    Outer_minus_Inner = Outer - Inner,
    Outer_minus_Mid   = Outer - Mid,
    pct_change_Mid_Inner   = 100 * (Mid - Inner)/Inner,
    pct_change_Outer_Inner = 100 * (Outer - Inner)/Inner,
    pct_change_Outer_Mid   = 100 * (Outer - Mid)/Mid
  )

difference_poci

emm_poci_year <- emmeans(nbin_Pocilloporidae_interaction, ~Year |Shelf, type = "response")
pairs(emm_poci_year, adjust = "tukey")
```

# Poritidae

## Shelf

```{r}
emm_pori_shelf <- emmeans(nbin_Poritid_interaction, ~Shelf | Year, type = "response")
#create dataframe
emm_pori_df <- as.data.frame(emm_pori_shelf) |> 
  rename(predicted_recruits = response)
# Contrast Dataframe
emm_pori_pair_df <- pairs(emm_pori_shelf, adjust = "tukey")

#Calcualte additive differences in total recruits
difference_pori <- emm_pori_df |> 
  select(Year, Shelf, predicted_recruits) |> 
  pivot_wider(names_from = Shelf, values_from = predicted_recruits) |> 
  mutate(
    Mid_minus_Inner   = Mid - Inner,
    Outer_minus_Inner = Outer - Inner,
    Outer_minus_Mid   = Outer - Mid,
    pct_change_Mid_Inner   = 100 * (Mid - Inner)/Inner,
    pct_change_Outer_Inner = 100 * (Outer - Inner)/Inner,
    pct_change_Outer_Mid   = 100 * (Outer - Mid)/Mid
  )
difference_pori
```

## Year 

```{r}
emm_pori_year <- emmeans(nbin_Poritid_interaction, ~Year |Shelf, type = "response")
#create dataframe
emm_pori_df <- as.data.frame(emm_pori_year) |> 
  rename(predicted_recruits = response)
# Contrast Dataframe
emm_pori_pair_df <- pairs(emm_pori_year, adjust = "tukey")

#Calcualte additive differences in total recruits
# difference_pori <- emm_pori_df |> 
#   select(Year, Shelf, predicted_recruits) |> 
#   pivot_wider(names_from = Shelf, values_from = predicted_recruits) |> 
#   mutate(
#     "21/22_minus"   = Mid - Inner,
#     Outer_minus_Inner = Outer - Inner,
#     Outer_minus_Mid   = Outer - Mid,
#     pct_change_Mid_Inner   = 100 * (Mid - Inner)/Inner,
#     pct_change_Outer_Inner = 100 * (Outer - Inner)/Inner,
#     pct_change_Outer_Mid   = 100 * (Outer - Mid)/Mid
#   )
```

All families

```{r}
nb_total_family_interaction <- glmmTMB(Total ~ Family * Shelf * Year_Collected + (1 | Reef/Site) ,
                        family = "nbinom2",
                        data = family_total_recruits)
```


```{r}
emmeans_total_family <- nb_total_family_interaction |> 
  emmeans(~Family | Shelf | Year_Collected, type = "response") 
pairs(emmeans_total_family, adjust = "tukey")
emmeans_total_family <- nb_total_family_interaction |> 
  emmeans(~Family | Year_Collected | Shelf, type = "response") 
pairs(emmeans_total_family, adjust = "tukey")
```


Position on tile

```{r}
nb_total_position_interaction <- glmmTMB(Total ~ Pos * Shelf * Year_Collected + (1 | Reef/Site) ,
                        family = "nbinom2",
                        data = position_total_recruits)
```

```{r}
emm_pos <- nb_total_position_interaction |> 
  emmeans(~Pos | Shelf | Year_Collected, type = "response")
pairs(emm_pos, adjust = "tukey")
emm_pos <- nb_total_position_interaction |> 
  emmeans(~Pos | Year_Collected| Shelf , type = "response")
pairs(emm_pos, adjust = "tukey")
```


