---
title: "PIT and tile Models"
author: "Monique White"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lme4)
library(lmerTest)
library(car)
library(emmeans)
library("FactoMineR")
library("factoextra")
library(FactoMineR)
library(factoextra)
library(vegan) #to do NMDS
library(PCAmixdata)
library(ggfortify)
library(glmmTMB) # Generalized Linear Mixed Models using Template Model Builder
library(DHARMa) # Diagnostics for Hierarchical (multi-level/mixed) regression models
library(ggpubr)
library(ggeffects) #to be able to do ggpredict
library(ggh4x) # to specify x and y axis if desired
library(MuMIn) #model selection function


# Import and clean data
## Recruitment data
Coral_settlement_nGBR_CS <- read.csv("~/Larval recruitment resources/Data Analysis/Coral-Settlement-Northern-GBR/Coral settlement_nGBR_CS.csv") %>%
  mutate(across(15:29, ~replace_na(.x, 0))) # Read in data

Coral_settlement_nGBR <- Coral_settlement_nGBR_CS %>% 
  filter(Shelf.posn != "Coral Sea", #remove coral sea data
        !Obs %in% c(1499, 1621, 1622)) #Remove loose tiles with heavy biofouling

Coral_settlement_nGBR <- Coral_settlement_nGBR %>% 
  rename("Shelf"= Shelf.posn,
         "Year_Collected"= Year..Jan.,
         "Site_#"= Site..,
         "Acroporidae" =Acropora,
         "Pocilloporidae" = Pocillopora,
         "Poritid" = Porites) |> 
  mutate(Year_Collected = factor(Year_Collected))
  

Coral_settlement_nGBR <- Coral_settlement_nGBR |>
  filter(Shelf == "Outer" | (Shelf %in% c("Inner", "Mid") & Tile %in% as.character(1:10)))

Coral_settlement_nGBR$Year_Collected <- factor(Coral_settlement_nGBR$Year_Collected)

Coral_settlement_nGBR <- Coral_settlement_nGBR |> 
  mutate(
    Year = case_when(
      Year_Collected == "2022" ~ "2021-22",
      Year_Collected == "2023" ~ "2022-23",
      Year_Collected == "2024" ~ "2023-24",
      Year_Collected == "2025" ~ "2024-25",
      Year_Collected == "2026" ~ "2025-26"
  )) |> 
mutate(
  notes = case_when(
    notes %in% c("dislodged", "dislodged tile", "dettached tile") ~ "Dislodged",
    notes %in% c("lots of tube worms") ~ "Lots of tube worms",
    TRUE ~ notes
  ))

Coral_settlement_nGBR <- Coral_settlement_nGBR |> 
mutate(
  notes = case_when(
    !notes %in% c("Dislodged", "Lots of tube worms")~"No notes",
    TRUE ~ notes
  ))
Coral_settlement_nGBR <- Coral_settlement_nGBR |> 
  filter(notes != "Dislodged")

# Benthic Data

PIT <- read_csv("PIT_50m.csv") %>%
  mutate(across(8:91, ~replace_na(.x, 0)))# Read in data

PIT <- PIT %>% 
  filter(Year %in% c("2021-22", "2022-23", "2023-24", "2024-25", "2025-26"))

PIT <- PIT |> 
  mutate(
    Site = case_when(
      Site %in% c("Vicky-HS", "Vickys") ~ "Vicky-HS",
      Site %in% c("Turtle Beach", "TurtleB-CooksP") ~ "TurtleB-CooksP",
      Site %in% c("Lag2-Trimodal", "Lagoon") ~ "Lag2-Trimodal",
      Site == "Turtle South - Front (Sargassum)" ~ "TS_Crest",
      Site == "Turtle South - Coral" ~ "TS_Back",
      Site == "Turtle North - front" ~ "TN_Crest",
      TRUE ~ Site
    ))


PIT<- PIT |> 
  mutate(
    Shelf = factor(Shelf),
    Reef = factor(Reef),
    Site = factor(Site))

join <- PIT |> 
  group_by(Year, Shelf, Reef, Site) |> 
  summarise(
    mean_acro = mean(Acroporidae),
    sd_acro = sd(Acroporidae),
    mean_poci = mean(Pocilloporidae),
    sd_poci = sd(Pocilloporidae),
    mean_por = mean(Poritidae),
    sd_por = sd(Poritidae),
    mean_hc_oth = mean(prop_other_hc)*100,
    sd_hc_oth = sd(prop_other_hc)*100,
    mean_b_macroalgae = mean(`Brown Macroalgae`),
    sd_b_macroalgae = sd(`Brown Macroalgae`),
    mean_r_macroalgae = mean(`Red Macroalgae`),
    sd_r_macroalgae = sd(`Red Macroalgae`),
    mean_g_macroalgae = mean(`Green Macroalgae`),
    sd_g_macroalgae = sd(`Green Macroalgae`),
    mean_turf = mean(Turf),
    sd_turf = sd(Turf),
    PIT = n()
  )

Combined <- left_join(Coral_settlement_nGBR, join)
```

# Acroporidae


```{r}
pois_fixed <- glmmTMB(Acroporidae ~ Shelf + Year_Collected + mean_acro + (1 | Reef/Site), 
      family = "poisson", data = Combined)

nbin_fixed <- glmmTMB(Acroporidae ~ Shelf + Year_Collected + mean_acro + (1 | Reef/Site), 
        family = "nbinom2", data = Combined)

zbin_fixed <- glmmTMB(Acroporidae ~ Shelf + Year_Collected + mean_acro + (1 | Reef/Site),
                      ziformula = ~1,
        family = "nbinom2", data = Combined)

pois_interaction <- glmmTMB(Acroporidae ~ Shelf * Year_Collected * mean_acro + (1 | Reef/Site), 
      family = "poisson", data = Combined)

nbin_interaction <- glmmTMB(Acroporidae ~ Shelf * Year_Collected * mean_acro + (1 | Reef/Site), 
        family = "nbinom2", data = Combined)

zbin_interaction <- glmmTMB(Acroporidae ~ Shelf * Year_Collected * mean_acro + (1 | Reef/Site),
                      ziformula = ~1,
        family = "nbinom2", data = Combined)
```

```{r}
simA1 <- simulateResiduals(pois_fixed)
testResiduals(simA1)

simA2 <- simulateResiduals(nbin_fixed)
testResiduals(simA2)

simA3 <- simulateResiduals(zbin_fixed)
testResiduals(simA3)

simA4 <- simulateResiduals(pois_interaction)
testResiduals(simA4)

simA5 <- simulateResiduals(nbin_interaction)
testResiduals(simA5)

simA6 <- simulateResiduals(zbin_interaction)
testResiduals(simA6)
```

```{r}
model.sel(pois_fixed, pois_interaction, nbin_fixed, nbin_interaction, zbin_fixed, zbin_interaction)
```

```{r}
summary(nbin_interaction)
```

```{r}
em_res <- emmeans(nbin_interaction, ~Shelf*mean_acro)

pairs(em_res, adjust = "tukey") 
```

```{r}
em_res <- emmeans(nbin_interaction, ~Year_Collected*mean_acro)

pairs(em_res, adjust = "tukey") 
```


# Pocilloporidae

```{r}
pois_fixed <- glmmTMB(Pocilloporidae ~ Shelf + Year_Collected + mean_poci + (1 | Reef/Site), 
      family = "poisson", data = Combined)

nbin_fixed <- glmmTMB(Pocilloporidae ~ Shelf + Year_Collected + mean_poci + (1 | Reef/Site), 
        family = "nbinom2", data = Combined)

zbin_fixed <- glmmTMB(Pocilloporidae ~ Shelf + Year_Collected + mean_poci + (1 | Reef/Site),
                      ziformula = ~1,
        family = "nbinom2", data = Combined)

pois_interaction <- glmmTMB(Pocilloporidae ~ Shelf * Year_Collected * mean_poci + (1 | Reef/Site), 
      family = "poisson", data = Combined)

nbin_interaction <- glmmTMB(Pocilloporidae ~ Shelf * Year_Collected * mean_poci + (1 | Reef/Site), 
        family = "nbinom2", data = Combined)

zbin_interaction <- glmmTMB(Pocilloporidae ~ Shelf * Year_Collected * mean_poci + (1 | Reef/Site),
                      ziformula = ~1,
        family = "nbinom2", data = Combined)
```

```{r}
simPC1 <- simulateResiduals(pois_fixed)
testResiduals(simPC1)

simPC2 <- simulateResiduals(nbin_fixed)
testResiduals(simPC2)

simPC3 <- simulateResiduals(zbin_fixed)
testResiduals(simPC3)

simPC4 <- simulateResiduals(pois_interaction)
testResiduals(simPC4)

simPC5 <- simulateResiduals(nbin_interaction)
testResiduals(simPC5)

simPC6 <- simulateResiduals(zbin_interaction)
testResiduals(simPC6)
```

```{r}
model.sel(pois_fixed, pois_interaction, nbin_fixed, nbin_interaction, zbin_fixed, zbin_interaction)
```

```{r}
summary(nbin_interaction)
```

```{r}
em_res <- emmeans(nbin_interaction, ~Shelf*mean_poci)

pairs(em_res, adjust = "tukey") 
```

```{r}
em_res <- emmeans(nbin_interaction, ~Year_Collected*mean_poci)

pairs(em_res, adjust = "tukey") 
```


# Poritidae

```{r}
pois_fixed <- glmmTMB(Poritid ~ Shelf + Year_Collected + mean_por + (1 | Reef/Site), 
      family = "poisson", data = Combined)

nbin_fixed <- glmmTMB(Poritid ~ Shelf + Year_Collected + mean_por + (1 | Reef/Site), 
        family = "nbinom2", data = Combined)

zbin_fixed <- glmmTMB(Poritid ~ Shelf + Year_Collected + mean_por + (1 | Reef/Site),
                      ziformula = ~1,
        family = "nbinom2", data = Combined)

pois_interaction <- glmmTMB(Poritid ~ Shelf * Year_Collected * mean_por + (1 | Reef/Site), 
      family = "poisson", data = Combined)

nbin_interaction <- glmmTMB(Poritid ~ Shelf * Year_Collected * mean_por + (1 | Reef/Site), 
        family = "nbinom2", data = Combined)

zbin_interaction <- glmmTMB(Poritid ~ Shelf * Year_Collected * mean_por + (1 | Reef/Site),
                      ziformula = ~1,
        family = "nbinom2", data = Combined)
```

```{r}
simPR1 <- simulateResiduals(pois_fixed)
testResiduals(simPR1)

simPR2 <- simulateResiduals(nbin_fixed)
testResiduals(simPR2)

simPR3 <- simulateResiduals(zbin_fixed)
testResiduals(simPR3)

simPR4 <- simulateResiduals(pois_interaction)
testResiduals(simPR4)

simPR5 <- simulateResiduals(nbin_interaction)
testResiduals(simPR5)

simPR6 <- simulateResiduals(zbin_interaction)
testResiduals(simPR6)
```

```{r}
model.sel(pois_fixed, pois_interaction, nbin_fixed, nbin_interaction, zbin_fixed, zbin_interaction)
```

```{r}
summary(nbin_interaction)
```

```{r}
em_res <- emmeans(nbin_interaction, ~Shelf*mean_por)

pairs(em_res, adjust = "tukey") 
```

```{r}
em_res <- emmeans(nbin_interaction, ~Year_Collected*mean_por)

pairs(em_res, adjust = "tukey") 
```