---
title: "Summary Statistics"
author: "Monique White"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lme4)
library(lmerTest)
library(car)
library(emmeans)
library("FactoMineR")
library("factoextra")
library(FactoMineR)
library(factoextra)
library(vegan) #to do NMDS
library(PCAmixdata)
library(ggfortify)
library(glmmTMB) # Generalized Linear Mixed Models using Template Model Builder
library(DHARMa) # Diagnostics for Hierarchical (multi-level/mixed) regression models
library(ggpubr)
library(ggeffects) #to be able to do ggpredict
library(ggh4x) # to specify x and y axis if desired
library(MuMIn) #model selection function
library(ggrepel)


# Import and clean data
## Recruitment data
Coral_settlement_nGBR_CS <- read.csv("~/Larval recruitment resources/Data Analysis/Coral-Settlement-Northern-GBR/Coral settlement_nGBR_CS.csv") %>%
  mutate(across(15:29, ~replace_na(.x, 0))) # Read in data

Coral_settlement_nGBR <- Coral_settlement_nGBR_CS %>% 
  filter(Shelf.posn != "Coral Sea", #remove coral sea data
        !Obs %in% c(1499, 1621, 1622)) #Remove loose tiles with heavy biofouling

Coral_settlement_nGBR <- Coral_settlement_nGBR %>% 
  rename("Shelf"= Shelf.posn,
         "Year_Collected"= Year..Jan.,
         "Site_#"= Site..,
         "Acroporidae" =Acropora,
         "Pocilloporidae" = Pocillopora,
         "Poritid" = Porites) |> 
  mutate(Year_Collected = factor(Year_Collected))
  

Coral_settlement_nGBR <- Coral_settlement_nGBR |>
  filter(Shelf == "Outer" | (Shelf %in% c("Inner", "Mid") & Tile %in% as.character(1:10)))

Coral_settlement_nGBR$Year_Collected <- factor(Coral_settlement_nGBR$Year_Collected)

Coral_settlement_nGBR <- Coral_settlement_nGBR |> 
  mutate(
    Year = case_when(
      Year_Collected == "2022" ~ "2021-22",
      Year_Collected == "2023" ~ "2022-23",
      Year_Collected == "2024" ~ "2023-24",
      Year_Collected == "2025" ~ "2024-25",
      Year_Collected == "2026" ~ "2025-26"
  )) |> 
mutate(
  notes = case_when(
    notes %in% c("dislodged", "dislodged tile", "dettached tile") ~ "Dislodged",
    notes %in% c("lots of tube worms") ~ "Lots of tube worms",
    TRUE ~ notes
  ))

Coral_settlement_nGBR <- Coral_settlement_nGBR |> 
mutate(
  notes = case_when(
    !notes %in% c("Dislodged", "Lots of tube worms")~"No notes",
    TRUE ~ notes
  ))

Coral_settlement_nGBR <- Coral_settlement_nGBR |> 
  filter(notes != "Dislodged")

Pocilloporidae <- Coral_settlement_nGBR %>% 
  select(Year_Collected, Shelf, 
         Reef, Site, Tile, 
         Pocilloporidae, Top_Pocil, 
         Under_Pocil, Side_Pocil, total)

Pocilloporidae_orientation <- Pocilloporidae %>% 
  rename(Top = Top_Pocil,
                   Bottom = Under_Pocil,
                   Side = Side_Pocil,
         Recruits_per_tile = total)

Pocilloporidae_orientation <- Pocilloporidae_orientation %>% 
  pivot_longer(cols = 7:9,
               names_to = "Tile_Surface",
               values_to = "Recruits")

Acroporidae <- Coral_settlement_nGBR %>% 
  select(Year_Collected, Shelf, 
         Reef, Site, Tile, 
         Acroporidae, Top_Acr, 
         Under_Acr, Side_Acr, total)

Acroporidae_orientation <- Acroporidae %>% 
  rename(Top = Top_Acr,
                   Bottom = Under_Acr,
                   Side = Side_Acr,
         Recruits_per_tile = total)

Acroporidae_orientation <- Acroporidae_orientation %>% 
  pivot_longer(cols = 7:9,
               names_to = "Tile_Surface",
               values_to = "Recruits")

Poritid <- Coral_settlement_nGBR %>% 
  select(Year_Collected, Shelf, 
         Reef, Site, Tile, 
         Poritid, Top_Por, Under_Por, 
         Side_Por, total)

Poritidae_orientation <- Poritid %>% 
  rename(Top = Top_Por,
                   Bottom = Under_Por,
                   Side = Side_Por,
         Recruits_per_tile = total) 

Poritidae_orientation <- Poritidae_orientation %>% 
  pivot_longer(cols = 7:9,
               names_to = "Tile_Surface",
               values_to = "Recruits")


# Benthic Data

PIT <- read_csv("PIT_50m.csv") %>%
  mutate(across(8:91, ~replace_na(.x, 0)))# Read in data

PIT <- PIT %>% 
  filter(Year %in% c("2021-22", "2022-23", "2023-24", "2024-25", "2025-26"))

PIT <- PIT |> 
  mutate(
    Site = case_when(
      Site %in% c("Vicky-HS", "Vickys") ~ "Vicky-HS",
      Site %in% c("Turtle Beach", "TurtleB-CooksP") ~ "TurtleB-CooksP",
      Site %in% c("Lag2-Trimodal", "Lagoon") ~ "Lag2-Trimodal",
      Site == "Turtle South - Front (Sargassum)" ~ "TS_Crest",
      Site == "Turtle South - Coral" ~ "TS_Back",
      Site == "Turtle North - front" ~ "TN_Crest",
      TRUE ~ Site
    ))


PIT<- PIT |> 
  mutate(
    Shelf = factor(Shelf),
    Reef = factor(Reef),
    Site = factor(Site))

join <- PIT |> 
  group_by(Year, Shelf, Reef, Site) |> 
  summarise(
    mean_aco = mean(prop_acro),
    sd_aco = sd(prop_acro),
    mean_poci = mean(prop_poci),
    sd_poci = sd(prop_poci),
    mean_por = mean(prop_pori),
    sd_por = sd(prop_pori),
    mean_macroalgae = mean(Prop_macroalgae),
    sd_macroalgae = sd(Prop_macroalgae),
    PIT = n()
  )

Combined <- left_join(Coral_settlement_nGBR, join)

## Total recuits
total_recruits <- Coral_settlement_nGBR %>%
  select(Year_Collected, Shelf, Reef, Site, Acroporidae, Pocilloporidae, Poritid, Other) %>% 
  pivot_longer(cols = 5:8, names_to = "Family", values_to = "Total")

#Order so that Other is last in Family
total_recruits <- Coral_settlement_nGBR %>% 
  select(Year_Collected, Shelf, Reef, Site, Obs, Acroporidae, Pocilloporidae, Poritid, Other) %>% 
  pivot_longer(cols = 6:9, names_to = "Family", values_to = "Total") %>%
  mutate(Family = factor(Family, levels = c("Acroporidae", "Poritid","Pocilloporidae", "Other")))

total_recruits$Year_Collected <- as.factor(total_recruits$Year_Collected)

## Position on tile

position_total_recruits <- Coral_settlement_nGBR %>%
  select(2:9, 15:29, 32) %>% 
  pivot_longer(cols = 21:23, names_to = "Pos", values_to = "Total")

position_total_recruits <- position_total_recruits |> 
  mutate(Pos = case_when(
      Pos == "Top.Total" ~ "Top",
      Pos == "Side.Total" ~ "Side",
      Pos == "Under.Total" ~ "Bottom"
  ))
 
position_total_recruits <- position_total_recruits |>                           
mutate(Pos = factor(Pos, levels = c("Bottom", "Side", "Top")))

position_total_recruits <- left_join(position_total_recruits, join)

## Family recruitment data
family_total_recruits <- Coral_settlement_nGBR %>%
  select(2:13) %>% 
  pivot_longer(cols = 9:12, names_to = "Family", values_to = "Total") |> 
  mutate(Family = factor(Family, levels = c("Acroporidae", "Poritid","Pocilloporidae", "Other")))
```


# Summary Statistics

```{r echo=FALSE}
Coral_settlement_nGBR |> 
  summarise(total_tiles = n(),
            total_recruits = sum(total),
            total_acro = sum(Acroporidae),
            total_poci = sum(Pocilloporidae),
            total_poritidae = sum(Poritid),
            total_other = sum(Other),
            total_bottom = sum(Under.Total),
            total_side = sum(Side.Total),
            total_top = sum(Top.Total)) |> 
  knitr::kable()
```

Temporal statistics

```{r echo=FALSE}
Coral_settlement_nGBR |> 
  group_by(Year_Collected) |> 
  summarise(total_tiles = n(),
            total_recruits = sum(total),
            total_acro = sum(Acroporidae),
            total_poci = sum(Pocilloporidae),
            total_poritidae = sum(Poritid),
            total_bottom = sum(Under.Total),
            total_side = sum(Side.Total),
            total_top = sum(Top.Total)) |> 
  knitr::kable()
```

## Summary statistics
```{r}
Coral_settlement_nGBR |> 
  summarise(
    mean = mean(total),
    se = sd(total)/(n()^0.5),
    n= n()
  )

Coral_settlement_nGBR |> 
  group_by(Year) |> 
  summarise(
    mean = mean(total),
    se = sd(total)/(n()^0.5),
    n= n()
  )

#21/22 and 23/24
59.24022/27.15976

#22/23 and 23/24
59.24022/13.52571

#23/24 and 24/25
59.24022/20.56497


```

### By Shelf Position

```{r}
Coral_settlement_nGBR |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(total),
    se = sd(total)/(n()^0.5),
    n= n()
  )

55.520833/24.259740
55.520833/9.921397
```

Inner 

```{r}
Coral_settlement_nGBR |> 
  filter(Shelf == "Inner") |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(total),
    se = sd(total)/(n()^0.5),
    n= n()
  )

```

Mid

```{r}
Coral_settlement_nGBR |> 
  filter(Shelf == "Mid") |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(total),
    se = sd(total)/(n()^0.5),
    n= n()
  )
```

Outer

```{r}
Coral_settlement_nGBR |> 
  filter(Shelf == "Outer") |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(total),
    se = sd(total)/(n()^0.5),
    n= n()
  )
```

Year and Shelf
2022
```{r}
Coral_settlement_nGBR |> 
  filter(Year_Collected == "2022") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(total),
    se = sd(total)/(n()^0.5),
    n= n()
  )
```

2023 

```{r}
Coral_settlement_nGBR |> 
  filter(Year_Collected == "2023") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(total),
    se = sd(total)/(n()^0.5),
    n= n()
  )
```

2024 

```{r}
Coral_settlement_nGBR |> 
  filter(Year_Collected == "2024") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(total),
    se = sd(total)/(n()^0.5),
    n= n()
  )
```

2025

```{r}
Coral_settlement_nGBR |> 
  filter(Year_Collected == "2025") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(total),
    se = sd(total)/(n()^0.5),
    n= n()
  )
```

# Acroporidae

```{r}
Coral_settlement_nGBR |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Acroporidae),
    se = sd(Acroporidae)/(n()^0.5),
    n= n()
  )

# inner ver mid
47.754167/16.299107
# inner vs outer
47.754167/2.214953
```



```{r}
Coral_settlement_nGBR |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(Acroporidae),
    se = sd(Acroporidae)/(n()^0.5),
    n= n()
  )

#2022 and 2023
22.295302/7.393064

#2024 and 2022
47.145251/22.295302

#2024 and 2023
47.145251/7.393064

#2025 and 2024
47.145251/14.384181
```

```{r}
Coral_settlement_nGBR |>
  filter(Year_Collected == "2022") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Acroporidae),
    se = sd(Acroporidae)/(n()^0.5),
    n= n()
  )
```

```{r}
Coral_settlement_nGBR |>
  filter(Year_Collected == "2023") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Acroporidae),
    se = sd(Acroporidae)/(n()^0.5),
    n= n()
  )
```

```{r}
Coral_settlement_nGBR |>
  filter(Year_Collected == "2024") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Acroporidae),
    se = sd(Acroporidae)/(n()^0.5),
    n= n()
  )
```

```{r}
Coral_settlement_nGBR |>
  filter(Year_Collected == "2025") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Acroporidae),
    se = sd(Acroporidae)/(n()^0.5),
    n= n()
  )
```

Shelf
Inner
```{r}
Coral_settlement_nGBR |> 
  filter(Shelf == "Inner") |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(Acroporidae),
    se = sd(Acroporidae)/(n()^0.5),
    n= n()
  )

#22 and 23
48.65000/10.46667

#2022 and 2024
100.41667/48.65000
```

Mid

```{r}
Coral_settlement_nGBR |> 
  filter(Shelf == "Mid") |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(Acroporidae),
    se = sd(Acroporidae)/(n()^0.5),
    n= n()
  )
```

Outer

```{r}
Coral_settlement_nGBR |> 
  filter(Shelf == "Outer") |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(Acroporidae),
    se = sd(Acroporidae)/(n()^0.5),
    n= n()
  )
```

## Pocilloporidae

```{r}
Coral_settlement_nGBR |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Pocilloporidae),
    se = sd(Pocilloporidae)/(n()^0.5),
    n= n()
  )
```



```{r}
Coral_settlement_nGBR |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(Pocilloporidae),
    se = sd(Pocilloporidae)/(n()^0.5),
    n= n()
  )
```

```{r}
Coral_settlement_nGBR |>
  filter(Year_Collected == "2022") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Pocilloporidae),
    se = sd(Pocilloporidae)/(n()^0.5),
    n= n()
  )
```

```{r}
Coral_settlement_nGBR |>
  filter(Year_Collected == "2023") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Pocilloporidae),
    se = sd(Pocilloporidae)/(n()^0.5),
    n= n()
  )
```

```{r}
Coral_settlement_nGBR |>
  filter(Year_Collected == "2024") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Pocilloporidae),
    se = sd(Pocilloporidae)/(n()^0.5),
    n= n()
  )
```

```{r}
Coral_settlement_nGBR |>
  filter(Year_Collected == "2025") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Pocilloporidae),
    se = sd(Pocilloporidae)/(n()^0.5),
    n= n()
  )
```

Shelf
Inner
```{r}
Coral_settlement_nGBR |> 
  filter(Shelf == "Inner") |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(Pocilloporidae),
    se = sd(Pocilloporidae)/(n()^0.5),
    n= n()
  )
```

Mid

```{r}
Coral_settlement_nGBR |> 
  filter(Shelf == "Mid") |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(Pocilloporidae),
    se = sd(Pocilloporidae)/(n()^0.5),
    n= n()
  )
```

Outer

```{r}
Coral_settlement_nGBR |> 
  filter(Shelf == "Outer") |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(Pocilloporidae),
    se = sd(Pocilloporidae)/(n()^0.5),
    n= n()
  )
```

# Position on tile

```{r}
position_total_recruits |> 
  group_by(Pos) |> 
  summarise(
    mean = mean(Total),
    se = sd(Total)/(n()^0.5),
    n= n()
  )
```

```{r}
position_total_recruits |> 
  group_by(Pos, Shelf) |> 
  summarise(
    mean = mean(Total),
    se = sd(Total)/(n()^0.5),
    n= n()
  )
```

```{r}
position_total_recruits |> 
  group_by(Pos, Year_Collected) |> 
  summarise(
    mean = mean(Total),
    se = sd(Total)/(n()^0.5),
    n= n()
  )
```

```{r}
Coral_settlement_nGBR |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Top.Total),
    se = sd(Top.Total)/(n()^0.5),
    n= n()
  )
```



```{r}
Coral_settlement_nGBR |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(Top.Total),
    se = sd(Top.Total)/(n()^0.5),
    n= n()
  )
```

```{r}
Coral_settlement_nGBR |>
  filter(Year_Collected == "2022") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Top.Total),
    se = sd(Top.Total)/(n()^0.5),
    n= n()
  )
```

```{r}
Coral_settlement_nGBR |>
  filter(Year_Collected == "2023") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Top.Total),
    se = sd(Top.Total)/(n()^0.5),
    n= n()
  )
```

```{r}
Coral_settlement_nGBR |>
  filter(Year_Collected == "2024") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Top.Total),
    se = sd(Top.Total)/(n()^0.5),
    n= n()
  )
```

```{r}
Coral_settlement_nGBR |>
  filter(Year_Collected == "2025") |> 
  group_by(Shelf) |> 
  summarise(
    mean = mean(Top.Total),
    se = sd(Top.Total)/(n()^0.5),
    n= n()
  )
```

Shelf
Inner
```{r}
Coral_settlement_nGBR |> 
  filter(Shelf == "Inner") |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(Top.Total),
    se = sd(Top.Total)/(n()^0.5),
    n= n()
  )
```

Mid

```{r}
Coral_settlement_nGBR |> 
  filter(Shelf == "Mid") |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(Top.Total),
    se = sd(Top.Total)/(n()^0.5),
    n= n()
  )
```

Outer

```{r}
Coral_settlement_nGBR |> 
  filter(Shelf == "Outer") |> 
  group_by(Year_Collected) |> 
  summarise(
    mean = mean(Top.Total),
    se = sd(Top.Total)/(n()^0.5),
    n= n()
  )
```


