---
title: "Thesis Map Final"
author: "Monique White"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load required packages
library(tidyverse)   # data wrangling and ggplot
library(sf)          # Spatial data handling
library(gisaimsr)    # GIS data focused in the Great Barrier Reef
library(ggspatial)   # for scale bar & north arrow
library(ggtext)      # ggplot2-rendering with element_markdown()
library(ggnewscale)  # multiple fill and colour scales in ggplot2
library(maptiles)    # download and display map tiles
library(terra)       # spatial data analysis
library(scales)      # # for rgb() and hex color conversion
library(raster) # for map
library(ggspatial) 
library(sf)
library(dataaimsr)
library(gisaimsr)
library(ggrepel)
library(ozmaps)
library(raster) # for map
library(ggspatial) 
library(sf)
library(dataaimsr)
library(gisaimsr)
library(ggrepel)
#library(rgeos) # has been replaced by sf package
library(rnaturalearth)
library(rnaturalearthdata)
library(tidyverse)
library(ggpubr)
```

# Map of North Queensland

# Define bounding box for QLD
```{r}
NQLD_bbox <- sf::st_bbox(c(xmin = 142, xmax = 148,
                             ymin = -20, ymax = -10.5),
                           crs = 4326)
NQLD_bbox_sf <- sf::st_as_sfc(NQLD_bbox)

NQLD_tiles <- get_tiles(
  x = NQLD_bbox_sf,
  provider = "Esri.WorldImagery",
  crop = TRUE,
  zoom = 5
)


NQLD_df <- as.data.frame(NQLD_tiles, xy = TRUE)        # Convert to data frame for ggplot

# Take columns 3, 4, and 5, and divide values by 255 (values in them range from 0 to 255 because they're RGB values). This turns values into a scale 0-1
NQLD_df$fill <- rgb(NQLD_df[,3] / 255,
                      NQLD_df[,4] / 255,
                      NQLD_df[,5] / 255)


NGBR_rect <- data.frame(
  xmin = 144.95,
  xmax = 145.6,
  ymin = -14.95,
  ymax = -14.4
)
```

```{r}
NQLD_plot <- ggplot() +
  geom_raster(
    data = NQLD_df,
    aes(x = x, y = y, fill = fill)
  ) +
  
  geom_rect(
    data = NGBR_rect,
    aes(xmin = xmin, xmax = xmax,
        ymin = ymin, ymax = ymax),
    fill = NA,
    colour = "white",
    linewidth = 1,
    inherit.aes = FALSE
  ) +
  
  scale_fill_identity() +
  
  coord_equal(
    xlim = c(142, 148),
    ylim = c(-20, -10.5),
    expand = FALSE
  ) +
  # annotation_scale(
  #   height = unit(0.15, "cm"),
  #   location = "br",
  #   width_hint = 0.2,
  #   pad_x = unit(0.5, "cm"),
  #   pad_y = unit(0.4, "cm"),
  #   text_col = "white",
  #   text_cex = 0.4,
  #   bar_cols = c("white", "black")
  # ) +
  labs(x = "Longitude", y = "Latitude") +
  theme_minimal() +
  theme(panel.grid = element_blank())+
  theme(
    plot.margin = margin(5, 5, 5, 5),
    # axis.title.x = element_text(margin = margin(t = 5)),
    # axis.title.y = element_text(margin = margin(r = 5)),
    axis.title = element_blank(),
    axis.text = element_blank()
  )
```

```{r}
NQLD_plot
```

```{r}
library(readxl)
#coords <-   read_excel("Approximate_GPS_Study_Sites.xlsx",col_types = c("text", "numeric", "numeric", "text"))
NGBR_sites_for_coral_settlement_tiles <- read_excel("~/Larval recruitment resources/Maps/NGBR sites for coral settlement tiles.xlsx", 
                                                    col_types = c("text", "numeric", "numeric", "text", "text"))
coords <- NGBR_sites_for_coral_settlement_tiles |> 
  mutate(Lat = -abs(Lat),
    Site = factor(Site),
         shelf_pos = factor(Shelf_Position),
         Reef = factor(Reef))
#study.sites <- read.csv('Data/Lizard_Island_Sites.csv', header = TRUE)     # import data on study sites
study.sites <- janitor::clean_names(coords)                           # make all column names lowercase (specify package 'janitor' to avoid conflict with insight::clean_names())


# Convert study.sites to sf object with coordinates and assign CRS
study.sites.sf <- st_as_sf(study.sites, coords = c("long", "lat"), crs = 4326)

study.sites.sf.coords <- st_coordinates(study.sites.sf)
study.sites.sf$longitude <- study.sites.sf.coords[, 1]
study.sites.sf$latitude <- study.sites.sf.coords[, 2]
```

 # Inner Shelf
```{r}
# Inner shelf
inner_bbox <- sf::st_bbox(c(xmin = 145.15, xmax = 145.23,
                             ymin = -14.76, ymax = -14.68),
                           crs = 4326)
inner_bbox_sf <- sf::st_as_sfc(inner_bbox)

inner_tiles <- get_tiles(
  x = inner_bbox_sf,
  provider = "Esri.WorldImagery",
  crop = TRUE,
  zoom = 5
)
                     # Higher = more detail (max ~20)

inner_df <- as.data.frame(inner_tiles, xy = TRUE)        # Convert to data frame for ggplot

# Take columns 3, 4, and 5, and divide values by 255 (values in them range from 0 to 255 because they're RGB values). This turns values into a scale 0-1
inner_df$fill <- rgb(inner_df[,3] / 255,
                      inner_df[,4] / 255,
                      inner_df[,5] / 255)

inner.sites.sf <- study.sites.sf |> 
  filter(shelf_pos == "Inner")

Inner_shelf <- ggplot() +
  geom_raster(data = inner_df, aes(x = x, y = y, fill = fill)) +   # display satellite image
  scale_fill_identity() +
  new_scale_fill() + # this command from package 'ggnewscale' allows the use of multiple fill scales
  geom_point(data = inner.sites.sf,                                 # plot study sites
             aes(x = longitude,                                     # longitude of each site
                 y = latitude),                                   # fill color based on 'habitat' type
             size = 2.5,                                            # size of points (study sites)
             alpha = 0.8,                                           # transparency (0 = transparent, 1 = opaque)
             shape = 21,                                            # if shape = 21, it plots a point with a border
             fill = "#FF5003",
            color = "grey10",                                      # color of border of points
             show.legend = TRUE) +                                  # show legend for study sites
  #scale_fill_manual(values = c("Inner" = "#FF5003","Mid" = "gold", "Outer"= "darkorange"),guide = guide_legend(title = "Shelf Position")) +
  coord_sf(
    xlim = c(st_bbox(inner_bbox_sf)$xmin, st_bbox(inner_bbox_sf)$xmax),
    ylim = c(st_bbox(inner_bbox_sf)$ymin, st_bbox(inner_bbox_sf)$ymax),
    expand = FALSE
  )+
  annotation_scale(height = unit(0.15, "cm"), 
                   location = "br", 
                   width_hint = 0.2, 
                   pad_x = unit(0.5, "cm"),
                   pad_y = unit(0.4, "cm"),
                   text_col = "white",
                   text_cex = 0.4,
                   bar_cols = c("white", "black")) +
  scale_x_continuous(labels = seq(from=145.1, to= 145.3, by = 0.1),
                     breaks = seq(from=145.1, to= 145.3, by = 0.1))+
  scale_y_continuous(labels = seq(from=-14.5, to= -14.8, by = -0.1),
                     breaks =seq(from=-14.5, to= -14.8, by = -0.1))+
  labs(x = "Longitude", 
       y = "Latitude") +
  theme_minimal() +
  guides(fill = guide_legend(title = "Shelf Position", 
                             title.position = "top", 
                             label.position = "left", 
                             label.theme = element_text(size = 6)))
```

 # Mid Shelf
 
```{r}
# Mid Shelf
mid_bbox <- sf::st_bbox(c(xmin = 145.42, xmax = 145.51,
                            ymin = -14.63, ymax = -14.72),
                          crs = 4326)
mid_bbox_sf <- sf::st_as_sfc(mid_bbox)

mid_tiles <- get_tiles(
  x = mid_bbox_sf,
  provider = "Esri.WorldImagery",
  crop = TRUE,
  zoom = 14
)

mid_df <- as.data.frame(mid_tiles, xy = TRUE)        # Convert to data frame for ggplot

# Take columns 3, 4, and 5, and divide values by 255 (values in them range from 0 to 255 because they're RGB values). This turns values into a scale 0-1
mid_df$fill <- rgb(mid_df[,3] / 255,
                     mid_df[,4] / 255,
                     mid_df[,5] / 255)

# Filter study sites for mid-shelf
mid.sites.sf <- study.sites.sf |> 
  filter(shelf_pos == "Mid")

# ---- Plot Mid Shelf ----
Mid_shelf <- ggplot() +
  geom_raster(data = mid_df, aes(x = x, y = y, fill = fill)) +   # satellite imagery
  scale_fill_identity() +
  new_scale_fill() + 
  geom_point(data = mid.sites.sf,
             aes(x = longitude, 
                 y = latitude),
             size = 2.5,
             alpha = 0.8,
             shape = 21,
             fill = "gold",
             color = "grey10",
             show.legend = TRUE) +
  coord_sf(
    xlim = c(st_bbox(mid_bbox_sf)$xmin, st_bbox(mid_bbox_sf)$xmax),
    ylim = c(st_bbox(mid_bbox_sf)$ymin, st_bbox(mid_bbox_sf)$ymax),
    expand = FALSE
  ) +
  annotation_scale(height = unit(0.15, "cm"), 
                   location = "br", 
                   width_hint = 0.2, 
                   pad_x = unit(0.5, "cm"),
                   pad_y = unit(0.4, "cm"),
                   text_col = "white",
                   text_cex = 0.4,
                   bar_cols = c("white", "black")) +
  scale_x_continuous(labels = seq(from=145.4, to= 145.5, by = 0.1),
                     breaks = seq(from=145.4, to= 145.5, by = 0.1))+
  scale_y_continuous(labels = seq(from=-14.6, to= -14.8, by = -0.1),
                     breaks =seq(from=-14.6, to= -14.8, by = -0.1))+
  #annotation_north_arrow(height = unit(0.6, "cm"), 
                       #  width = unit(0.4, "cm"), 
                       #  location = "tr", 
                       #  which_north = "true", 
                       #  style = north_arrow_orienteering(
                       #    text_size = 8,
                       #    line_col = "white",
                       #    text_col = "white"
                       #  ),
                       #  pad_x = unit(0.5, "cm"), 
                       #  pad_y = unit(0.5, "cm")) +
  labs(x = "Longitude", 
       y = "Latitude") +
  theme_minimal() +
  theme(
    #axis.text.x = element_text(size = 6),
        #axis.text.y = element_text(size = 6),
        #axis.title.x = element_text(size = 7.5, margin = margin(t = 10)),
        #axis.title.y = element_text(size = 7.5, margin = margin(r = 6)),
        #legend.position = "bottom",
        #legend.background = element_rect(fill = "white"),
        #legend.margin = margin(l = 0.2, r = 0.2, t = 0.2, b = 0.2, unit = 'cm'),
        #legend.title = element_text(size = 6.5, face = "bold"),
        #legend.text = element_text(size = 5.5),
        #legend.key.spacing.y = unit(0.12, 'cm'),
        #legend.key.size = unit(0.12, 'cm')
  ) + 
  guides(fill = guide_legend(title = "Shelf Position", 
                             title.position = "top", 
                             label.position = "left", 
                             label.theme = element_text(size = 6)))

```
 
```{r}
Mid_shelf
```
 
 
 # Outer Shelf
```{r}
# Outer Shelf
outer_bbox <- sf::st_bbox(c(xmin = 145.44, xmax = 145.56,
                          ymin = -14.42, ymax = -14.54),
                        crs = 4326)
outer_bbox_sf <- sf::st_as_sfc(outer_bbox)

outer_tiles <- get_tiles(
  x = outer_bbox_sf,
  provider = "Esri.WorldImagery",
  crop = TRUE,
  zoom = 14
)

outer_df <- as.data.frame(outer_tiles, xy = TRUE)        # Convert to data frame for ggplot

# Take columns 3, 4, and 5, and divide values by 255 (values in them range from 0 to 255 because they're RGB values). This turns values into a scale 0-1
outer_df$fill <- rgb(outer_df[,3] / 255,
                   outer_df[,4] / 255,
                   outer_df[,5] / 255)

# Filter study sites for the outer shelf
outer.sites.sf <- study.sites.sf |>
  filter(shelf_pos == "Outer")

# ---- Plot Outer Shelf ----
Outer_shelf <- ggplot() +
  geom_raster(data = outer_df, aes(x = x, y = y, fill = fill)) +
  scale_fill_identity() +
  new_scale_fill() +
  geom_point(data = outer.sites.sf,
             aes(x = longitude, y = latitude),
             size = 2.5,
             alpha = 0.8,
             shape = 21,
             fill = "darkorange",
             color = "grey10",
             show.legend = TRUE) +
  coord_sf(
    xlim = c(st_bbox(outer_bbox_sf)$xmin, st_bbox(outer_bbox_sf)$xmax),
    ylim = c(st_bbox(outer_bbox_sf)$ymin, st_bbox(outer_bbox_sf)$ymax),
    expand = FALSE
  ) +
  annotation_scale(height = unit(0.15, "cm"), 
                   location = "br", 
                   width_hint = 0.2, 
                   pad_x = unit(0.5, "cm"),
                   pad_y = unit(0.4, "cm"),
                   text_col = "white",
                   text_cex = 0.4,
                   bar_cols = c("white", "black")) +
  scale_x_continuous(labels = seq(from=145.4, to= 145.6, by = 0.1),
                     breaks = seq(from=145.4, to= 145.6, by = 0.1))+
  scale_y_continuous(labels = seq(from=-14.3, to= -14.6, by = -0.1),
                     breaks =seq(from=-14.3, to= -14.6, by = -0.1))+
  labs(x = "Longitude", y = "Latitude") +
  theme_minimal() +
  theme() +
  guides(fill = guide_legend(title = "Shelf Position", 
                             title.position = "top", 
                             label.position = "left", 
                             label.theme = element_text(size = 6)))
```
 
 
```{r}
NGBR_b_box <- sf::st_bbox(c(
  xmin = 144.85, xmax = 145.7,
  ymin = -14.95, ymax = -14.35), crs = 4326)


NGBR_bbox_sf <- sf::st_as_sfc(NGBR_b_box)

NGBR_tiles <- get_tiles(
  x = NGBR_bbox_sf,
  provider = "Esri.WorldImagery",
  crop = TRUE,
  zoom = 10
)

NGBR_df <- as.data.frame(NGBR_tiles, xy = TRUE)        # Convert to data frame for ggplot

# Take columns 3, 4, and 5, and divide values by 255 (values in them range from 0 to 255 because they're RGB values). This turns values into a scale 0-1
NGBR_df$fill <- rgb(NGBR_df[,3] / 255,
                    NGBR_df[,4] / 255,
                    NGBR_df[,5] / 255)

Inner_rect <- data.frame(
  xmin = 145.15, 
  xmax = 145.23,
  ymin = -14.76, 
  ymax = -14.68)

Mid_rect <- data.frame(
 xmin = 145.42,
 xmax = 145.51,
 ymin = -14.63,
 ymax = -14.72 
)

Outer_rect <- data.frame(
  xmin = 145.44,
  xmax = 145.56,
  ymin = -14.42,
  ymax = -14.54
)

NGBR_plot <- ggplot() +
  geom_raster(
    data = NGBR_df,
    aes(x = x, y = y, fill = fill)
  ) +
    annotation_scale(
    height = unit(0.15, "cm"),
    location = "br",
    width_hint = 0.2,
    pad_x = unit(0.5, "cm"),
    pad_y = unit(0.4, "cm"),
    text_col = "white",
    text_cex = 0.4,
    bar_cols = c("white", "black")
  ) +
  geom_rect(
    data = Inner_rect,
    aes(xmin = xmin, xmax = xmax,
        ymin = ymin, ymax = ymax),
    fill = NA,
    colour = "#FF5003",
    linewidth = 1,
    inherit.aes = FALSE
  ) +
  geom_rect(
    data = Mid_rect,
    aes(xmin = xmin, xmax = xmax,
        ymin = ymin, ymax = ymax),
    fill = NA,
    colour = "gold",
    linewidth = 1,
    inherit.aes = FALSE
  ) +
  geom_rect(
    data = Outer_rect,
    aes(xmin = xmin, xmax = xmax,
        ymin = ymin, ymax = ymax),
    fill = NA,
    colour = "darkorange",
    linewidth = 1,
    inherit.aes = FALSE
  ) +
  scale_fill_identity() +
  coord_equal(
    xlim = c(144.85,145.7),
    ylim = c(-14.95, -14.35),
    expand = FALSE
  ) +
  labs(x = "Longitude", y = "Latitude") +
  theme_minimal() +
  theme(panel.grid = element_blank())+
  theme(
    #plot.margin = margin(5, 5, 5, 5),
    axis.title.x = element_text(margin = margin(t = 5)),
    axis.title.y = element_text(margin = margin(r = 5))
  )


NGBR_plot
```
 
Need to fix the scale on these ones..
```{r}
library(sf)
library(ggplot2)
library(ggspatial)
library(dplyr)

# ----------------------------
# 1. Define bbox in lon/lat
# ----------------------------
NGBR_b_box <- st_bbox(
  c(
    xmin = 144.85, xmax = 145.7,
    ymin = -14.95, ymax = -14.35
  ),
  crs = 4326
)

NGBR_bbox_sf <- st_as_sfc(NGBR_b_box)

# ----------------------------
# 2. Project bbox to UTM 55S
# (correct for ~145E, 15S)
# ----------------------------
utm_crs <- 32755  # WGS84 / UTM zone 55S

NGBR_bbox_utm <- st_transform(NGBR_bbox_sf, crs = utm_crs)

# ----------------------------
# 3. Get imagery tiles (projected)
# ----------------------------
NGBR_tiles <- get_tiles(
  x = NGBR_bbox_utm,
  provider = "Esri.WorldImagery",
  crop = TRUE,
  zoom = 10
)

# Convert tiles to dataframe for ggplot
NGBR_df <- as.data.frame(NGBR_tiles, xy = TRUE)

# RGB → hex colour
NGBR_df$fill <- rgb(
  NGBR_df[, 3] / 255,
  NGBR_df[, 4] / 255,
  NGBR_df[, 5] / 255
)

# ----------------------------
# 4. Define rectangles in lon/lat
# ----------------------------
Inner_rect <- st_as_sfc(st_bbox(
  c(xmin = 145.15, xmax = 145.23,
    ymin = -14.76, ymax = -14.68),
  crs = 4326
))

Mid_rect <- st_as_sfc(st_bbox(
  c(xmin = 145.42, xmax = 145.51,
    ymin = -14.72, ymax = -14.63),
  crs = 4326
))

Outer_rect <- st_as_sfc(st_bbox(
  c(xmin = 145.44, xmax = 145.56,
    ymin = -14.54, ymax = -14.42),
  crs = 4326
))

# Project rectangles to UTM
Inner_rect_utm <- st_transform(Inner_rect, utm_crs)
Mid_rect_utm   <- st_transform(Mid_rect, utm_crs)
Outer_rect_utm <- st_transform(Outer_rect, utm_crs)

# ----------------------------
# 5. Plot
# ----------------------------
NGBR_plot <- ggplot() +
  
  # Satellite imagery
  geom_raster(
    data = NGBR_df,
    aes(x = x, y = y, fill = fill)
  ) +
  
  scale_fill_identity() +
  
  # Rectangles
  geom_sf(
    data = Inner_rect_utm,
    fill = NA,
    colour = "#FF5003",
    linewidth = 1
  ) +
  geom_sf(
    data = Mid_rect_utm,
    fill = NA,
    colour = "gold",
    linewidth = 1
  ) +
  geom_sf(
    data = Outer_rect_utm,
    fill = NA,
    colour = "darkorange",
    linewidth = 1
  ) +
  
  # Correct scale bar (metres!)
  annotation_scale(
    location = "br",
    height = unit(0.15, "cm"),
    width_hint = 0.2,
    pad_x = unit(0.5, "cm"),
    pad_y = unit(0.4, "cm"),
    text_col = "white",
    text_cex = 0.4,
    bar_cols = c("white", "black")
  ) +
  
  # Use coord_sf (NOT coord_equal)
  coord_sf(
    crs = utm_crs,
    expand = FALSE
  ) +
  
  labs(
    x = "Longitude",
    y = "Latitude"
  ) +
  
  theme_minimal() +
  theme(
    panel.grid = element_blank(),
    axis.title.x = element_text(margin = margin(t = 5)),
    axis.title.y = element_text(margin = margin(r = 5))
  )

NGBR_plot

```

 
```{r}
NQLD_plot

NGBR_plot

Outer_shelf

Inner_shelf

Mid_shelf
# ggarrange(NQLD_plot, Outer_shelf, Inner_shelf, Mid_shelf)
```

```{r}
top_map <- ggarrange(NQLD_plot, NGBR_plot, widths = c(1,2))
bottom_map <- ggarrange(Inner_shelf, Mid_shelf, Outer_shelf, ncol = 3)

map <- ggarrange(top_map, bottom_map, ncol=1, heights = c(1.5, 1))
```

```{r}
ggsave(filename = "Thesis_Map.png",
       plot = map,
       width = 9.5,
       height = 9,
       units = "in",
       dpi = 300)
```

```{r}
library(sf)
library(ggplot2)
library(ggspatial)
library(dplyr)

# ----------------------------
# 1. Define Inner shelf bbox (lon/lat)
# ----------------------------
inner_bbox <- st_bbox(
  c(
    xmin = 145.15, xmax = 145.23,
    ymin = -14.76, ymax = -14.68
  ),
  crs = 4326
)

inner_bbox_sf <- st_as_sfc(inner_bbox)

# ----------------------------
# 2. Project bbox to UTM 55S
# ----------------------------
utm_crs <- 32755  # WGS84 / UTM zone 55S

inner_bbox_utm <- st_transform(inner_bbox_sf, utm_crs)

# ----------------------------
# 3. Get satellite tiles (projected)
# ----------------------------
inner_tiles <- get_tiles(
  x = inner_bbox_utm,
  provider = "Esri.WorldImagery",
  crop = TRUE,
  zoom = 14        # ↑ use high zoom for small area
)

# Convert tiles to data frame
inner_df <- as.data.frame(inner_tiles, xy = TRUE)

# RGB → hex colour
inner_df$fill <- rgb(
  inner_df[, 3] / 255,
  inner_df[, 4] / 255,
  inner_df[, 5] / 255
)

# ----------------------------
# 4. Filter + project study sites
# ----------------------------
inner.sites.sf <- study.sites.sf |>
  filter(shelf_pos == "Inner") |>
  st_transform(utm_crs)

# ----------------------------
# 5. Plot
# ----------------------------
Inner_shelf <- ggplot() +
  
  # Satellite imagery
  geom_raster(
    data = inner_df,
    aes(x = x, y = y, fill = fill)
  ) +
  scale_fill_identity() +
  
  # Study sites
  geom_sf(
    data = inner.sites.sf,
    shape = 21,
    size = 2.5,
    alpha = 0.8,
    fill = "#FF5003",
    color = "grey10"
  ) +
  
  # Correct scale bar (metres)
  annotation_scale(
    height = unit(0.15, "cm"),
    location = "br",
    width_hint = 0.2,
    pad_x = unit(0.5, "cm"),
    pad_y = unit(0.4, "cm"),
    text_col = "white",
    text_cex = 0.4,
    bar_cols = c("white", "black")
  ) +
  
  # Projected coordinate system
  coord_sf(
    crs = utm_crs,
    expand = FALSE
  ) +
  
  labs(
    x = "Easting (m)",
    y = "Northing (m)"
  ) +
  
  theme_minimal() +
  theme(
    panel.grid = element_blank()
  )

Inner_shelf

```

```{r}
library(sf)
library(ggplot2)
library(ggspatial)
library(dplyr)

# ----------------------------
# 1. Define Mid shelf bbox (lon/lat)
# ----------------------------
mid_bbox <- st_bbox(
  c(
    xmin = 145.42, xmax = 145.51,
    ymin = -14.72, ymax = -14.63
  ),
  crs = 4326
)

mid_bbox_sf <- st_as_sfc(mid_bbox)

# ----------------------------
# 2. Project bbox to UTM 55S
# ----------------------------
utm_crs <- 32755  # WGS84 / UTM zone 55S

mid_bbox_utm <- st_transform(mid_bbox_sf, utm_crs)

# ----------------------------
# 3. Get satellite tiles (projected)
# ----------------------------
mid_tiles <- get_tiles(
  x = mid_bbox_utm,
  provider = "Esri.WorldImagery",
  crop = TRUE,
  zoom = 14
)

# Convert tiles to data frame
mid_df <- as.data.frame(mid_tiles, xy = TRUE)

# RGB → hex colour
mid_df$fill <- rgb(
  mid_df[, 3] / 255,
  mid_df[, 4] / 255,
  mid_df[, 5] / 255
)

# ----------------------------
# 4. Filter + project study sites
# ----------------------------
mid.sites.sf <- study.sites.sf |>
  filter(shelf_pos == "Mid") |>
  st_transform(utm_crs)

# ----------------------------
# 5. Plot
# ----------------------------
Mid_shelf <- ggplot() +
  
  # Satellite imagery
  geom_raster(
    data = mid_df,
    aes(x = x, y = y, fill = fill)
  ) +
  scale_fill_identity() +
  
  # Study sites
  geom_sf(
    data = mid.sites.sf,
    shape = 21,
    size = 2.5,
    alpha = 0.8,
    fill = "gold",
    color = "grey10"
  ) +
  
  # Correct scale bar (metres)
  annotation_scale(
    height = unit(0.15, "cm"),
    location = "br",
    width_hint = 0.2,
    pad_x = unit(0.5, "cm"),
    pad_y = unit(0.4, "cm"),
    text_col = "white",
    text_cex = 0.4,
    bar_cols = c("white", "black")
  ) +
  
  # Projected coordinates
  coord_sf(
    crs = utm_crs,
    expand = FALSE
  ) +
  
  labs(
    x = "Easting (m)",
    y = "Northing (m)"
  ) +
  
  theme_minimal() +
  theme(
    panel.grid = element_blank(),

  # Axis text inside the panel
  axis.text.x = element_text(
    colour = "white",
    margin = margin(t = -8)   # move labels upward (inside)
  ),
  axis.text.y = element_text(
    colour = "white",
    margin = margin(r = -8)   # move labels rightward (inside)
  ),

  # Optional: keep axis titles readable
  axis.title.x = element_text(colour = "white"),
  axis.title.y = element_text(colour = "white")
)

Mid_shelf
```


```{r}

```

